vich_uploader:
    db_driver: orm

    mappings:
       products: 
           uri_prefix: '%upload_actu_image%'
           upload_destination: '%kernel.project_dir%/public%upload_actu_image%'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           delete_on_update: false
           delete_on_remove: false
    
       products2:
           uri_prefix: '%upload_event_image%'
           upload_destination: '%kernel.project_dir%/public%upload_event_image%'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           delete_on_update: false
           delete_on_remove: false