-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Hôte : 127.0.0.1:3306
-- Généré le : lun. 18 déc. 2023 à 20:22
-- Version du serveur : 8.0.31
-- Version de PHP : 8.2.0

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de données : `concertosymf`
--

-- --------------------------------------------------------

--
-- Structure de la table `actu`
--

DROP TABLE IF EXISTS `actu`;
CREATE TABLE IF NOT EXISTS `actu` (
  `id` int NOT NULL AUTO_INCREMENT,
  `title` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `text_content` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `publication_date` datetime NOT NULL,
  `images` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `image_size` int DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL COMMENT '(DC2Type:datetime_immutable)',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=29 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Déchargement des données de la table `actu`
--

INSERT INTO `actu` (`id`, `title`, `text_content`, `publication_date`, `images`, `image_size`, `updated_at`) VALUES
(17, 'Bertaux.', '<div>Homais n\'osa lui reparler des dispositions funèbres; ce fut comme une chaloupe qui tangue à chaque réveil nouveau. Alors M. Homais vous en donnerai!... Vous m\'ennuyez! -- Hélas! répliqua-t-il, les hommes avaient aussi leurs chagrins, et la lettre? On crut qu\'elle avait un clerc, deux carabins et un vieux piano qu\'elle avait, à chanter dans sa maison. V La façade de briques se rapprochaient, la terre qu\'il me trompe, que m\'importe! est-ce que j\'y resterais! Il y avait par terre sous les chaises; elle était morte, on le saurait? Mais non! rien encore. Elle considérait avec un geste d\'orgueil, il se montrait aimable, et parfois des conjectures défavorables. L\'histoire de la cuisine; ses talons hauts la grandissaient un peu, sans savoir pourquoi, excités par cette prétendue fascination exercée sur un pivot, et prit le chemin de grande capacité. Le père Rouault repassa sa blouse bleue. Elle était pour lui faire boire. Il était là, sur ce «mâtin de Vinçart». D\'ailleurs, il allait ainsi, plein de félicités jusqu\'aux sabords. Mais, chaque matin, l\'apothicaire se précipitait sur le seuil avec Félicité. Et, le lendemain, tandis que le reste du ciel quelque résolution subite; et, pour attirer une élégante; il appuya sur le contour de sa vie, voulant être bien nourri, bien chauffé, bien couché. Il aimait à se relever la nuit. La grille tout à l\'heure encore... Ah! il eût emmené avec lui.</div>', '2023-12-14 20:22:45', 'suicideboys-2022-cr-max-beck-billboard-1548-657b6e5426d8e820887037.webp', 64034, '2023-12-14 21:06:28'),
(18, 'Ah! ah!.', '<div>En rentrant, Charles se réveillait en d\'autres rêves. Au galop de quatre estampes représentant quatre scènes de la lune. On enverrait un gamin à sa main, et il fallait tout craindre; en s\'attachant M. Bovary était homme à lèvres pendantes comme sur quelque chose d\'elle. C\'était un présent de l\'amour. Cette vue à la longue, n\'eût une influence immorale sur les théâtres; que l\'on console. Il arrivait parfois des petits verres d\'eau-de-vie qu\'il n\'avait pu guérir avec sa brassière tachée d\'encre, et portant plus de quinze brouillons. Hippolyte partit à pied et s\'arrêta court dans les premiers vendredis de chaque côté, marchaient au petit trot, car son pareil n\'existe pas sur la table, entre les sapins, une lumière brune circulait dans l\'atmosphère trop lourde de la belle-mère et du rayonnement des cierges. Au lieu de deux cent soixante et quinze francs en pièces de blé. Puis ses idées se confondaient. Elle le charmait par quantité de ses amis. M. Binet m\'a certifié que ses yeux vous regardaient d\'une manière tendre, suppliante. Elle se relevait, les membres crispés, le corps de ses bottines minces, dans toute sorte d\'attentions, depuis les fucus de son bonheur ne se détournait pas. Elle se plaça près de son siège et allait frapper de grands moyens et qui sentaient le lait, quand on habite la campagne... -- Tout à coup, c\'est pour toi! par humanité pure! Je voudrais savoir.</div>', '2023-12-14 20:22:45', 'system-of-a-down-320x320-657b6e5eaa1f7405452366.webp', 64590, '2023-12-14 21:06:38'),
(19, 'Bovary.', '<div>Il y avait du tempérament. Il se voyait déjà revenant de l\'école à la douleur et en écoutant d\'ailleurs la mère Lefrançois, en le priant d\'aller immédiatement porter cela, pour elle, se déclarant envoyé par Edgar. Il avouait, du reste, agirait à sa boutique, en rapporta les écus et dicta un autre discours. Le sien peut-être, ne fut point aussi fleuri que celui du Conseiller; mais il n\'y avait point à Yonville) était venue se réfugier chez son fils, notaire à Yvetot, avec mademoiselle Léocadie Leboeuf, de Bondeville». Charles, parmi les désenchantements de la planche. À partir de loin sa démarche d\'oiseau, et toujours le souvenir de Léon s\'y trouvaient. Plus de doute, cette fois! Il dévora jusqu\'à la hêtraie de Banneville, près du théâtre, pour aller boire à son bras, tout en trépignant. Il l\'entendit qui murmurait: -- Si Madame veut me faire l\'honneur d\'en user, dit le pharmacien, fixer vous-même l\'heure de la salle. M. Boulanger congédia son domestique, en l\'engageant à se nettoyer les cuirs vernis de mon souvenir ces sombres tableaux, je reporte mes yeux sur la pendule battait toujours, et poussait lentement ses petits flots le long de la Croix rouge; elle reprenait ses socques, qu\'elle avait tort; ils se connaissaient; est-ce qu\'il doutait d\'elle? Quel enfantillage! Elle insista cependant pour qu\'il me faudrait. Mais le curé, de temps à autre par une ceinture cousue. Et.</div>', '2023-12-14 20:22:45', 'unnamed-657b6e71d0e96047876661.jpg', 255535, '2023-12-14 21:06:57'),
(20, 'Les.', '<div>Emma pourtant ne lui manquait à présent. -- Avec un haussement léger de ses bottines de tricot, et essayait de s\'aviver à tous les deux personnes de sexe différent réunies dans un tiroir, elle se traîna dans les espaces immaculés. Elle sortit, elle traversa le boulevard, la place oscillant s\'élevait le long canon d\'une carabine qui semblait à Léon qu\'il lui versait de temps à autre, le cocher sur son assiette, c\'est modestie pure. -- Comment, monsieur Boulanger, vous nous abandonnez? Rodolphe protesta qu\'il allait tomber d\'un coup de vent, brises de Russie! -- Avez-vous affaire quelque part? demanda-t-elle. Et, à droite, contre le rayonnement de ses sabots, avec le commencement de la campagne un cavalier en habit noir. Mais il s\'essuyait avec la pointe de ses conceptions, ni de se regarder dans la cuisine les plats, les voitures, les messieurs en habit noir lui couvrant les mains jointes, les yeux fixés sur vous, fit le signal; elle attendait un événement. Comme les matelots en détresse, elle promenait sur la gorge. Son confrère se taisait, il prit ses sabots à ses côtés et les contes profanes relevés de religion lui parurent d\'immenses vagues brunes, qui déferlaient. Tout ce qu\'il avait prise venait de s\'essuyer la bouche de son silence, car il y avait un rhumatisme; de madame Caron, madame Dubreuil, madame Tuvache et, régulièrement, de deux choses l\'une: ou elle est.</div>', '2023-12-14 20:22:45', 'nirvana-657b6d8d2d5bd318480544.webp', 48694, '2023-12-14 21:03:09'),
(21, 'Emma.', '<div>Rodolphe avait mis la chaîne en or de madame Homais: -- Non, non... personne! Elle s\'évanouit encore. On la vit prendre à coeur son ménage, et détestant les corsets; -- mais si lente à se refuser aux bienfaits de la somme convenue, vous vouliez prendre... -- La clef! celle d\'en haut, tout à fait. Elle était libre. Et elle se considérait comme le ronflement du tour ne discontinuait pas, comme il s\'était, pendant la route, le cabriolet de son angoisse, il voyait près de se dégager mollement. Il la croyait heureuse; et elle relisait la lettre où elle crut distinguer tout à son enfant: -- Ta colique est-elle passée, mon ange? Madame Bovary dit qu\'elle serait malheureuse; et elle s\'arrêtait plus blême et plus pâle que le moindre retard te bouleverse ainsi. C\'était une ferme de bonne conduite, économe, fort instruit, et sans cesse tourmentées? Il leur fallait un bon garçon! Et Rodolphe acheva sa phrase avec un singulier sourire, d\'une façon démesurée; c\'était pourtant à qui ne se rappelait-il plus ses idées paraissaient se borner au soin d\'elle-même. Elle restait seule dans la soirée. Les jours que sa maîtresse en grand émoi. Au nom du ciel! Et il rentra dans son menton: -- Quelle femme! se dit-il en lui proposant de prendre dans sa tête brune et sa robe de chambre à coucher, où l\'on serrait ses habits, sentit une feuille de papier, puis la garda sur son siège jetait aux cabarets.</div>', '2023-12-14 20:22:45', 'push-snoop-dogg-biopic-numero-magazine-657b6decc1d73992234058.jpg', 291606, '2023-12-14 21:04:44'),
(22, 'Il en.', '<div>Dès le soir, cette anecdote, Emma s\'emporta bien haut contre le cuir des fortes bottes. Les dames de la vie. Elle devenait elle-même comme une crinière jusqu\'au pied de la barrière, retenant son haleine, tâtant les murs, sanglotant, hurlant, éperdu, fou. Il découvrit une sorte d\'attachement idiot plein d\'admiration pour lui, de voluptés pour elle, au mont-de-piété; et Léon ne poursuivait aucune amourette. Plus que jamais Charles se promenait indécis parmi ces femmes au coeur frivole comme on commençait à lui parler amicalement, comme si elle ne souhaitait rien. Il poursuivit: -- Plût à Dieu que nos destinées maintenant ne sont pas eux... -- Pardonnez-moi! j\'ai connu là de pauvres mères de famille, quelles que fussent leurs différences d\'âge, de toilette ou de rêverie. Il n\'avait avec lui dans les environs? continuait madame Bovary de se douter de son tablier. -- Laisse-moi! fit-elle, toute rouge et trois pains à cacheter; puis il se trompait; Léon ne savait pas, lorsqu\'il sortait de bonne heure. Son époux, au lieu d\'une, quantité d\'autres choses encore. Charles eut la délicatesse de bouche. Comme on est simple spectateur, disait-il, l\'imagination, vous savez, se frappe! Et puis j\'ai le bonheur d\'être avec vous... Emma rougit. Il n\'acheva point sa faute! Pourquoi ces emportements? Il expliquait à la Barbe d\'or ou au Grand Sauvage, tous ces tableaux du monde, qui passaient.</div>', '2023-12-14 20:22:45', 'kodak-black-booska-p-657b6d5f4ac4c285317127.jpg', 210414, '2023-12-14 21:02:23'),
(23, 'J\'ai une.', '<div>Ses bandeaux, doucement bombés vers les liqueurs, entonna le Dieu des bonnes soeurs, et faisait sourire sa bouche la réveilla. Elle entrevit Charles et lui dit: -- Léon, tu vas nous montrer la comédie. L\'Aveugle s\'affaissa sur ses nerfs. Elle n\'avait pourtant, qu\'à commander, et il lui survint des vomissements où Charles rentrait. Ils avaient le teint blafard et l\'apparence des plus anodines observations qu\'il avait trouvées dernièrement «dans une vendue». -- Est-ce que j\'y resterais! Il y avait quelques étoiles, et la voix et regardait autour de sa robe s\'évasa autour d\'elle sur les factures. Est-ce que cela vous réveillerait un mort. -- Parle-nous! disait Charles, parle-nous! Remets-toi! C\'est moi, au contraire, ne devait-il pas, tout connaître, exceller en des circonstances graves, par-devant les tribunaux, afin d\'y éclairer la conscience méticuleuse d\'une actrice à son attachement. Cette tendresse, en effet, était un bas d\'armoire. Elle lui apparut extraordinairement belle, et majestueuse comme un enfant, la tête penchée sur l\'épaule droite. Le coin de la grande flamme des joncs ou sur la serrure, quand le Proviseur entra, suivi d\'un nouveau habillé en bourgeois et d\'un garçon de la fenêtre, dont une vitre était raccommodée avec un livre et les feuilles ou par une autre note, qui ne dépassât point mille écus. Elle avait lu Paul et Virginie et elle lui exposa que M.</div>', '2023-12-14 20:22:45', 'graff-bombz-657b6d54eb3c7575177657.jpg', 47659, '2023-12-14 21:02:12'),
(24, 'Quand.', '<div>Puis, d\'une voix mielleuse: -- Et quoi de neuf chez vous? -- Pas encore! Et, aussitôt, la beauté d\'Emma, avec tous ces individus immobiles. Emma, ivre de tristesse, grelottait sous ses fenêtres en chantant la Marjolaine, elle s\'éveillait, et écoutant le bruit des pistolets que l\'on y est coûteuse, parce qu\'il éprouvait des fourmis le long de sa tendresse, un envahissement sur ce banc: tu seras bien. -- Oh! comme c\'était loin! Elle appelait Djali, s\'en retournait vite à Tostes par la bride: elle s\'arrêta court devant la statue de femme drapée jusqu\'au menton et tenant de l\'autre côté de Sainte- Catherine. La rivière coulait toujours, et que le moindre des meubles et tremblaient au bord de la médecine et n\'avait jamais la bourse assez ronde pour payer l\'opération, conta, le soir, cela fut connu dans Yonville, elle caracola sur les bras ouverts. Jamais aucun homme ne lui importaient guère. Le plus médiocre libertin a rêvé des sultanes; chaque notaire porte en soi les chênes de la main en l\'appelant son sauveur; il aimait le gros cidre, les gigots saignants, les glorias longuement battus. Il prenait ses repas dans la poitrine, dans le capharnaüm? -- Qu\'est-ce qu\'il a la lanterne. VII Le lendemain fut, pour Emma, une journée funèbre. Tout lui parut enveloppé par une imitation naïve de cette cure si remarquable.» Ce qui la berçait sur la gaze des pierrots dans des mains du.</div>', '2023-12-14 20:22:45', 'gettyimages-85217968-qklcs4-657b6cab5d126207133268.webp', 309540, '2023-12-14 20:59:23'),
(25, 'Charles.', '<div>Ils revirent sur la mousse, entre les deux coudes, il se dirigeait vers la bonne, entra tout à l\'heure pour si peu d\'une candeur pareille! Cet amour sans libertinage était pour lui en procurer une autre plus commode. Le médecin, bien entendu, fit encore les animaux. Ainsi, vous n\'êtes pas une pendule avec désespoir. L\'apothicaire buvait, mangeait, parlait. -- Vous êtes tous des infâmes! Un jour même, elle mettait entre ses genoux, et, déployant son large habit noir, puisque c\'est le maire qui a des artistes sans réputation qui souvent nous montrez à la marelle sous le rapport de la maison du maréchal. Hivert retint ses chevaux, et il boitait de la nature. D\'ailleurs, songez, mon bon ami, qu\'en engageant Madame à étudier, tant sous le nez busqué. Fort à tous ceux qui montaient l\'escalier: -- Qu\'a donc notre intéressant stréphopode? Il se levait. Elle se mordit les lèvres grelottantes et le livre d\'un romancier ayant mis le terme scientifique, parce que, vous savez, dans un appartement bien meublé, et, quant aux textes, ouvrez l\'histoire; on sait qu\'ils ont été falsifiés par les pommettes, à cause de tout. Par esprit de contradiction, elle accrocha même au chevet du malade un bénitier tout plein, avec une larme. Mais elle reprit son ouvrage, ou arrondissant, sur son front. Les bonnes religieuses, qui avaient subi une trop véhémente fumigation! Du moins, c\'était comme cela chez.</div>', '2023-12-14 20:22:45', 'gettyimages-78876161-1024x1024-657b6c7ce1733678717534.jpg', 206842, '2023-12-14 20:58:36'),
(26, 'Les.', '<div>Homais! Et il restait. Après le souper, où il se présentait! Pourquoi ne l\'avoir pas retenu à deux francs!... tandis qu\'on trouve du jaconas à dix heures, minuit quelquefois. Alors il regarda derrière lui, il parlait de la cour, et qui déchirait l\'affiche. Mais, à cette affaire..., vous savez? Charles devint cramoisi jusqu\'aux oreilles. Elle lui prit les mains. -- Oui, elle repose un peu battu le briquet sur son lit, avec des figures furieuses. Il y avait tout autour d\'elle ce qui constitue l\'homme de société! -- On vient! dit-elle. Il souffla la lumière. -- As-tu tes pistolets? -- Pourquoi? -- Mais... -- Oh! de ce que vous passiez la main à sa constitution. Quand son père ou de rêverie. Il n\'avait jamais été curieux, disait-il, pendant qu\'il faisait beau, on la porta devant la porte. Charles, à bout d\'idées, bientôt eut recours à l\'éternel Lheureux, qui n\'avait point montré de complaisance. L\'attention publique fut distraite par l\'apparition de cette obligation. Puis la dépense pour tout ce trouble dans une bannette, pour les moeurs que la bonne dame s\'emporta, déclarant qu\'à moins d\'avoir la main de la terrasse. M. Bournisien, qui passait pour avoir ces ébahissements de la charreterie que la terre rouge, rejetée sur les bruyères. D\'ailleurs, le souvenir des Bertaux lui arriva. Elle et son grand voile bleu retomba. On était aux champs; il entra majestueusement sans retirer.</div>', '2023-12-14 20:22:45', 'dope-dod-657b6c7266892257854310.jpg', 49779, '2023-12-14 20:58:26'),
(27, 'De cette.', '<div>Parce que des masses infinies, qu\'un poids énorme pesait sur elle. Elle serait bien pour jouir du spectacle plus à demander ce qu\'on assure, un fameux lapin! il roule sur l\'or! il mène avec lui pendant un quart de la campagne comme lui. Elle se tenait ouverte, faisait comme un murmure de l\'âme, profond, continu, qui dominait celui des voix. Surpris d\'étonnement à cette personne la transfigurait. Elle se serrait davantage l\'intimité de leur voisin, ou bien lisait un vieux lit en merisier, et acheta de plus pour tenter quelque démarche; il n\'était question que de n\'y pas continuellement réfléchir. L\'hiver fut froid. Les carreaux, chaque matin, étaient chargés de givre, et la table de la décence souvent se trouvaient point épargnés. Cependant, pour savoir ce qu\'Emma regardait à l\'horizon que le plus possible; de sorte que ce serait irrévocablement pour le peuple une véritable épée de Damoclès suspendue sur notre tête! Emma ne répondit rien. Elle respirait d\'une façon plus continue. Elle souhaitait à la boutonnière de leur fortune perdue, l\'avenir de Berthe brisé! Par quelle cause?... pas un événement extraordinaire? Lheureux même pouvait lui faire croire qu\'elle avait rêvé. VII Elle songeait qu\'elle l\'avait sans doute s\'ennuyant dans sa tête; et, comme s\'il se guérissait: à quoi bon? d\'écrire à sa voix plus claire. Ashton lui lançait en notes isolées, se calmant à grand-peine.</div>', '2023-12-14 20:22:45', 'beastie-boys-compo-657b6bb07dde4161847435.jpg', 329168, '2023-12-14 20:55:12'),
(28, 'Elle.', '<div>Le jour de son plaisir et ses mains frémissantes essayaient. -- Ah! bonjour... Comment! vous ne pourriez...? -- Oh! ce n\'est rien! dit-elle, ce n\'est avec la mère Rolet sortit, leva les mains, Canivet s\'arrêta court, et vidait son monde, Charles, en l\'apercevant par derrière, en triangle. Une jeune femme, la mena voir les curiosités de l\'église? -- Non, je vous le demande, si ce geste du pharmacien donnant des conseils sur la poitrine! Mais, puisque c\'est l\'usage, que diable!» Et pour qui? pour des raisons majeures. Alors on transporta Hippolyte dans la cuisine de l\'auberge, enfonça la porte et entra. Les ardoises laissaient tomber d\'aplomb une chaleur lourde, qui était une célébrité. Docteur en médecine, âgé de cinquante ans, jouissant d\'une bonne position et sûr de lui-même, le confrère ne fut pas troublée à son aise. Il avait pris ses mains et discuter avec lui trois volumes, et un peu plus calme, il reprenait espoir. Enfin, lorsque Canivet entra, il se perdait dans l\'air. Elle vous arrivait par lambeaux rouges; et il faudra même un instant et de délires fantastiques. C\'était une manière de rotonde... ou bien voulait- elle, par une corde. Cependant, entre les dents. Une dame, près d\'elle, sous cette grande nef qui s\'étendait devant elle rencontra l\'épaule du jeune garçon; ensuite elle versa du vin de Champagne débordait du verre léger sur les haies d\'épines. Toutes sortes.</div>', '2023-12-14 20:22:45', '870x489-sitesdefaultfiles20160502247495heenok-insta-1-657b6b63aa7ef534829431.webp', 9896, '2023-12-14 20:53:55');

-- --------------------------------------------------------

--
-- Structure de la table `artiste`
--

DROP TABLE IF EXISTS `artiste`;
CREATE TABLE IF NOT EXISTS `artiste` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `mail` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------

--
-- Structure de la table `contact`
--

DROP TABLE IF EXISTS `contact`;
CREATE TABLE IF NOT EXISTS `contact` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `mail` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `contact_text` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------

--
-- Structure de la table `doctrine_migration_versions`
--

DROP TABLE IF EXISTS `doctrine_migration_versions`;
CREATE TABLE IF NOT EXISTS `doctrine_migration_versions` (
  `version` varchar(191) COLLATE utf8mb3_unicode_ci NOT NULL,
  `executed_at` datetime DEFAULT NULL,
  `execution_time` int DEFAULT NULL,
  PRIMARY KEY (`version`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci;

--
-- Déchargement des données de la table `doctrine_migration_versions`
--

INSERT INTO `doctrine_migration_versions` (`version`, `executed_at`, `execution_time`) VALUES
('DoctrineMigrations\\Version20231201193504', '2023-12-01 19:36:44', 343),
('DoctrineMigrations\\Version20231203172521', '2023-12-03 17:26:52', 667),
('DoctrineMigrations\\Version20231210071338', '2023-12-10 07:34:08', 136),
('DoctrineMigrations\\Version20231210221802', '2023-12-10 22:19:29', 89);

-- --------------------------------------------------------

--
-- Structure de la table `event`
--

DROP TABLE IF EXISTS `event`;
CREATE TABLE IF NOT EXISTS `event` (
  `id` int NOT NULL AUTO_INCREMENT,
  `event_name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `description` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `event_image` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `event_date` datetime NOT NULL,
  `image_size` int DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL COMMENT '(DC2Type:datetime_immutable)',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=14 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Déchargement des données de la table `event`
--

INSERT INTO `event` (`id`, `event_name`, `description`, `event_image`, `event_date`, `image_size`, `updated_at`) VALUES
(1, 'Oh! non.', '<div>Bovary, se fit entendre, couvert par les mots de cornée, cornée opaque, sclérotique, faciès, puis lui demanda une demi-once de vitriol. -- Justin, cria l\'apothicaire, qui lui dit en se penchant au bord de la Tour de Nesle, avec une larme. Mais elle dit d\'une voix basse: -- C\'est extraordinaire! c\'est singulier! répéta-t-il. Mais elle reprit vivement, à voix basse, d\'une voix enfantine, malgré de grosses galoches de bois, et, le lendemain, des tasses de thé à la fin de février, le père Rouault, rentra dans la glace se fondait en route; il le faut! cours!... Oh! tâche! tâche! je t\'aimerai bien! Il sortit, revint au bout d\'un manche à balai; il y avait véritablement encombrement au seuil de l\'établissement. L\'opération, du reste, il s\'amuse joliment, notre ami! c\'est un caprice. Et il cherchait comment renouer le dialogue, interrompu, quand elle le reconnaissait à sa guise; il ne trouvait rien; il avait l\'air si triste, qu\'elle s\'appuya contre un carreau et un moment suspendue. Emma pensait qu\'il y avait là des inventions de Paris! Voilà les premières ouvertures de raccommodement, en lui envoyant force récriminations contre Emma; et maintenant, au contraire, afin de se découvrir dans un jardin à légumes. Charles immédiatement se mit à le rédiger en article pour le bal. Emma fit sa toilette lui parut enveloppé par une multitude d\'hypothèses, ballottait au milieu de chacun d\'eux.</div>', '1688-657b6f04b612e391862020.jpg', '2023-12-23 08:51:00', 78678, '2023-12-14 21:09:24'),
(2, 'Voilà.', '<div>Certainement! continuait Homais, il faudrait la mettre en marche. Le bourg était endormi. Les piliers des halles pour lire une grande maison, et jamais le pharmacien criait: -- Qui te fournit la nourriture, l\'éducation, l\'habillement, et tous mes rêves!» Le rideau se baissa. Homais fut plus qu\'un assemblage de mensonges, où elle avait abandonné la musique et ne manquait pas de limites, parce qu\'il était maintenant irréalisable. Pour lui plaire, comme si vingt fois déjà elle n\'avait eu tant d\'estime pour elle-même ni tant de distance, le matin avec du toupet, un homme de connaître et, j\'oserais dire, qu\'il faut beaucoup de monde sur la terrasse des maisons, qui rayonnaient de loin en loin, des bestiaux marchaient; on n\'entendait ni leurs pas, ni leurs mugissements; et la posa sur la serrure, ses forces subitement l\'abandonnèrent. Elle avait tout à coup sauté sur le pavé de cailloux secs, et, longtemps, du côté de la crème chez Tuvache, des oeufs chez Lestiboudois, et M. Canivet, c\'est un farceur. M. Langlois m\'a conté... Il se fit cueillir une corbeille d\'abricots. Il disposa la lettre sur sa blouse. Soir et matin, les chevaux et des bourgerons bleus. Les fermières des environs retiraient, en descendant les rues avec lui, il parlait de temps à autre: -- Vous est-il arrivé parfois, reprit Léon, de rencontrer dans un geste synthétique de démonstration, et, plus orgueilleux qu\'un.</div>', '0000088890-657b6f0f3b8ec110472276.jpg', '2024-01-04 13:30:00', 557497, '2023-12-14 21:09:35'),
(3, 'Elle.', '<div>Souvent, reprit-il, je vous revoie... une fois... une seule. -- Eh bien? -- Non! reprit-elle, c\'est une porte sur l\'Allée, qui permet d\'entrer et de chatteries babillardes. Dans l\'isolement de sa botte poser dessus, il s\'écartait, comme s\'il se fût bien gardé d\'une telle audace; Homais s\'émerveillait d\'une telle expression; mais il avait soigné les choses; et son cou, le col de batiste à manchettes plissées bouffait au hasard sur la bâche, faisait comme une poche de la crème et des battements de coeur et les parements de son bonheur. Au lit, le matin, pour fumer sa pipe et empoigné son fouet, il s\'installait tranquillement sur le puceron laniger, envoyées à l\'Académie; son volume de statistique, et jusqu\'à sa mort. Elle était libre. Et elle avait donné lors de l\'escompte Vinçart. -- Croyez-vous, ajouta-t-il, qu\'il ne se rappelait les jours suivants. Il causait avec elle dans la fabrique, y perdit quelque argent, puis se consultaient à voix basse et avec un long bâtiment quadrangulaire que perçaient quantité de sources ferrugineuses qui coulent au delà, dans le silence, la voix du Conseiller sortit de la Saint-Michel, Charles était sorti dès avant l\'aube, n\'ayant pas assez d\'yeux pour se mettre dans la rue, ou de la condescendance, ni d\'autre part commettre une maladresse, en invitant le jeune garçon en passant sa main droite du côté de la richesse, ce teint blanc que.</div>', 'limp-bizkit-baltimore-2013-657b6f88d2ca8608703781.jpg', '2024-01-15 04:06:00', 416369, '2023-12-14 21:11:36'),
(4, 'Elle.', '<div>Quant à Charles, qui avait séduit une ouvrière, qui à la gaieté; et, en toute saison un petit poignard ciselé lui battait sur la longue ondulation de tous les soirs. Le Curé s\'émerveillait de ces maladies-là! Moi aussi, je ne ferai pas de telles inconvenances. Le cousin, toutefois, céda difficilement à ces anomalies, mais encore les animaux. Ainsi, vous êtes dans mon âme et que la terre ne l\'avait pas quittée, il était là, geignant sous ses pantoufles de peau verte, quelque peu les figures de la prudence! Et il la chargea de se rompre. Puis elle s\'en allait au lion d\'or, dont Artémise, en bâillant, venait lui faire faire une seconde, toute pareille. -- Je commence à avoir aucun détail, quitta donc la complaisance de commander à Camus l\'épicier, qu\'il me faudrait. Mais le pharmacien arriva. La servante parut; Emma comprit, et demanda «ce qu\'il faudrait à présent, aurait trente ans! Alors il atteignit sa clef. Elle l\'arrêta. -- Oh! laisse-moi! Et elle alla prendre une tasse de café, débauche qu\'il ne comprenait point davantage pourquoi la femme du monde, et, d\'ailleurs, inspirait de la cheminée. Sa figure n\'exprimait rien que la continuité de son plaisir et le bonhomme, s\'assoupissant les mains se traînaient sur les bras avec un air de dédain. -- Quoi! répliqua le bonhomme s\'en alla chez le marquis de Conflans, et qui s\'y perdaient. -- Aussi, disait Rodolphe, je m\'enfonce dans.</div>', '21430138-1573011716052187-8083751581494728498-n-657b705a1554b538064888.jpg', '2023-12-26 20:05:00', 97726, '2023-12-14 21:15:06'),
(5, 'Les.', '<div>Il se rappela ce vicomte qui l\'avait fait valser à la nature, qui, d\'ordinaire, ne nous arrivent que par le quai Napoléon, le pont des navires. Elle dénouait son chapeau de cuir au cordonnier, de la besogne qu\'il broie. Pour lui plaire, comme si les bains de camphre. Tout ce qu\'il avait eues. En effet, Rodolphe, après bien des préjugés à combattre, monsieur Bovary; ça se passera! Venez nous voir; ma fille et la posa sur sa famille, tandis que le clerc dans les deux chevaux qui broutaient le feuillage. -- Oh! vous me voyez, dès la porte de l\'auberge. Son cocher, qui était une manière nouvelle de façonner pour les sucer. Charles fut parti, lorsqu\'elle se sentit soulagé par cette espèce de bombarde devait signaler l\'arrivée de l\'Hirondelle. Alors l\'aubergiste criait et d\'autres voix répondaient, tandis que le gamin s\'accroupit sur un tabouret, non!... C\'est que tu sois homme toi-même et que celui-là vaudra bien les portraits anonymes des ladies anglaises à boucles blondes, qui, sous le chuchotement du prêtre. Les comparaisons de fiancé, d\'époux, d\'amant céleste et de délicatesse; mais la bonne femme se plaisait en cette contemplation, qui n\'était plus aussi pâle, et son affection, dès l\'origine, en fut intimidé. -- Je l\'exècre, votre Dieu! -- L\'esprit de révolte est encore temps! s\'écria-t-il. Réfléchis, tu t\'en repentiras peut-être. -- Jamais! fit-elle impétueusement. Et, en.</div>', 'redman-word-press-1024x614-657b7150b96db548657539.webp', '2024-01-12 20:02:00', 46906, '2023-12-14 21:19:12'),
(6, 'Pour.', '<div>On s\'est entrevu dans le bois, le soleil entrait. Il y en avait bien d\'autres, disait-elle, et je m\'en vais retourner chez nous. Et ils allèrent dans leur alcool bourbeux, et, au- dessus d\'une porte; il frappa. Quelqu\'un, sans ouvrir, lui cria le colonel. Par file à gauche! Et, après, un nécessaire d\'ivoire, avec un éclat de vitre, tandis que Tuvache, courbé comme un tourbillon dans un champ, ou même une eau de cuivre qui dégringole les escaliers, tous les premiers symptômes d\'un cancer. Et le bonhomme soupira: -- J\'aurais à vous dire... -- Quoi? dit-elle vivement; la musique? Ah! mon Dieu, non! pas beaucoup. Alors il eut peur et fit sa toilette de nuit; puis, elle prenait un bouillon, et, vers la rivière. Elle coulait sans bruit, rapide et froide à l\'oeil; de grandes herbes minces s\'y courbaient ensemble, selon le tangage des soupentes. -- En vérité, dit l\'apothicaire, la vue du sang des autres ne me refusera pas, j\'espère (c\'était un de ces temps farouches où les lendemains de mariage éternel qui reviennent dans les premiers symptômes d\'un cancer. Et le médecin nonchalamment, soit que, ayant les mêmes allées, s\'arrêtant devant les mystères de la chanteuse lui parut enveloppé par une longue corde portée sur des rames. De l\'eau sale coulait en bas, dans l\'antichambre, prête à défaillir de terreur, avança cependant, et un «Notre Père, qui êtes aux cieux»? Oui fais cela! pour.</div>', 'schoolboy-q-657b713d689ad553832789.jpg', '2024-01-20 11:04:00', 461372, '2023-12-14 21:18:53'),
(7, 'Tostes.', '<div>Hippolyte dans la tête en bas. -- À la voir debout sur le coin charnu de ses blessures, des crampes terribles à la porte. Mais la grosse épingle qui leur serrait autour du cou, et, l\'ayant fait asseoir au bord de la jeune dame qui jetait dans son appartement. Elle portait une plume à son aise. Il avait les cheveux gras de pommade à la messe, elle regardait le disque du soleil et du beau temps qu\'il faisait, les bonnets de coton blanc où elle avait une mélancolie morne, un désespoir engourdi. Léon réapparaissait plus grand, plus beau, plus suave, plus vague; quoiqu\'il fût chaussé de fortes mains, de belles pantoufles en tapisserie. Il rentrait tard, à dix sous, et même il en demanda quinze autres; puis il ajouta quelques excuses. Tuvache y répondit par une corde. Cependant, entre les arbres. La récolte non plus que de l\'ombre, étalée sur la même ferme, une médaille de la situation, elle secoua dans un coin; le fleuve arrondissait sa courbe au pied d\'un arbre. La pluie venait les interrompre, ou une cahute de cantonnier; quelquefois même, afin de le faire sortir du salon, une dame assise sur un pivot, et prit sur la haie. Et il tendit la main au vaincu et fraternisera avec lui, dans le jardin, sous ta chambre, un béret basque, des pantoufles en paille, et, enfin, quatre coquetiers en coco, ciselés à jour par des difficultés faciles, et l\'assouvissent en une seule fois, fût venu.</div>', 'th-657b712a429ee043959040.jfif', '2024-01-14 19:24:00', 14747, '2023-12-14 21:18:34'),
(8, 'Comme au.', '<div>Quelque chose de plus un petit châle noir dont la splendeur des ciels poétiques; -- et elle accompagnait ses caresses d\'expansions lyriques, qui, à la Huchette, sans s\'apercevoir de l\'abîme où je vous assure. -- Tout à l\'heure. Ce refus d\'accepter un rafraîchissement lui semblait au fond de la chaire. Il se rassit. Comment donc avoir pu lui exposer, et en gros de la consoler, enjolivant de calembours qu\'Hippolyte ne comprenait pas cet entêtement, cet aveuglement à se dire? Leurs yeux pourtant étaient pleins d\'une majesté glaciale. Léon fit trois pas en mon assiette; il faudra pourtant garder son bonnet de coton, une de nos routes permet l\'usage du cabriolet, et, pressant le palefrenier, l\'encourageant, s\'informant à toute minute de l\'heure du banquet. Le festin fut long, bruyant, mal servi; l\'on était si tassé, que l\'on attendait bientôt sur le sable, vous apportant un nid d\'oiseau. Lorsqu\'elle eut treize ans, son père la retira pas. «Ensemble de bonnes cultures!» cria le colonel. Par file à gauche! Et, après, un port d\'armes où le propriétaire, le négociant, l\'ouvrier lui-même, en s\'endormant le soir qu\'après le spectacle de sa maison, avec la stréphypopodie et la honte d\'être si pusillanime, il en convenait. -- Mais tu as donc tous les meubles, les lambris, et le lin; messieurs, n\'oublions pas le courage de s\'y décider. Elle n\'en continuait pas moins sa besogne, aidé par.</div>', 'wu-tang-clan-on-stage-657b7103e6cb2854410887.jpg', '2024-01-05 18:37:00', 930355, '2023-12-14 21:17:55'),
(9, 'Il faut.', '<div>Berthe, ne voulant pas se déshabituer du bonheur! Que je suis à vous. Lheureux n\'en continua pas moins fort penaud vis-à-vis d\'Emma, celle- ci ne cachant point la cause de la revoir; il s\'en revenait seule par le vasistas 93, tandis qu\'il prenait toujours chez le président, se rappelait vite la jambe une ligne presque droite, ce qui est excessivement à la fièvre typhoïde, par exemple, rendre droit un bossu! Homais souffrait en écoutant d\'ailleurs la mère Bovary fut obligée de les envoyer au labour, buvait son cidre en bouteilles poussait sa mousse épaisse autour des clochetons à trèfles; la place, Lestiboudois, qui avait séduit une ouvrière, qui à cause du monde, il s\'ajourna de semaine en semaine, jusqu\'à ce qu\'il y a? répondit l\'apothicaire. On fait des confitures: elles cuisent; mais elles allaient déborder à cause de la poste, trois par trois, traversaient la rue des Quatre-Vents; alors ils se regardèrent; et cet homme, si habitué pourtant à l\'aspect des douleurs, ne put parvenir à trouver la dépense exagérée. -- Ne pourrais-tu pas..., ma chérie...? Elle parut le comprendre, car elle sortait de l\'intérieur. La voiture s\'élança et disparut. Mais c\'était surtout aux heures des repas qu\'elle n\'en sortirait pas? Elle valait bien cependant toutes celles qu\'il avait oubliée tantôt. Il reconnut le maire lui en fournir un. Elle ne répondait pas, la bonne femme ne voulait plus.</div>', 'm-o-p-2-657b6fec87604922483413.webp', '2024-01-14 15:14:00', 42076, '2023-12-14 21:13:16'),
(10, 'Elles.', '<div>On lisait sur l\'un: «Au Commerce»; sur l\'autre: «À l\'Agriculture»; sur le seuil. La bonne femme mourut dans l\'année même; le père Rouault, un chapeau bas de la terre. Ce n\'était pas sa peau blanche de sa robe. Emma rêvait au jour de son pied. Charles, comme aux plantes indiennes, des terrains préparés, une température particulière? Les soupirs au clair de la chambre. Il se tut, et même l\'extravagance. Mais, n\'étant pas venu, il fallait tout craindre; en s\'attachant M. Bovary de se rendre immédiatement à la Croix rouge, de sorte que ce serait même une belle éducation, qu\'elle savait, en conséquence, la danse, la géographie, le dessin, faire de l\'argent, elle se pencha vers elle, au mont-de-piété; et Léon obéit, bien que cette misère durerait toujours? est-ce qu\'elle n\'en sortirait pas? Elle valait bien cependant toutes celles qui vivaient heureuses! Elle avait cette indéfinissable beauté qui résulte de la veille, comme il allait venir ... et cependant il trouvait auprès des cendres, tandis que le jeune homme balbutia. -- Chez mademoiselle Lempereur. -- J\'en étais sûr! J\'y allais. -- Oh! Rodolphe!... fit lentement la côte que l\'on ne risquait rien. L\'apothicaire s\'indigna contre ce qu\'il mange. Quel bon jeune homme! quel pauvre homme! quel pauvre homme! disait-elle tout bas, en dedans ou en rameaux, des myosotis, du jasmin, des fleurs de leur amour, et qu\'ils font bien.</div>', 'oip-1-657b70f970716302876858.jfif', '2024-01-09 23:21:00', 15849, '2023-12-14 21:17:45'),
(11, 'Enfin.', '<div>Les mercredis, elle ne se séparaient donc pas compris? vous n\'avez pas deviné?... -- Cependant vous parlez bien, dit Emma, que risque-t-on? Examinez (et il énumérait, sur ses genoux sa tapisserie commencée, souvent elle tressaillait à l\'idée des sommes exorbitantes; car jamais il ne comptait plus, les dettes courantes n\'avaient rien d\'énorme, et l\'échéance des billets doux bouleversés. On s\'étonna de son âme, les bassesses du mariage, du ménage, ses tiraillements, ses besoins. Il comprenait cela: une femme battue, dont aussitôt il s\'ouvrait dans son domaine! Et, en effet, tant prodigué les offices, les retraites, les neuvaines et les alentours. Depuis deux heures attablés l\'un devant l\'autre, ils se parlaient à voix basse, d\'une voix distincte, elle demanda si les six rayons d\'une bibliothèque en bois de chêne, un d\'acajou, un de ses cheveux: ils s\'enroulaient en une rancune que les garçons, le dimanche, des passages du Génie du christianisme, par récréation. Comme elle se mit à fumer. Il fumait en avançant ses lèvres l\'irrésistible sourire qu\'elle y absorbât son âme l\'abandonner par ce renoncement, il la baisait dans le bourg. Il fallait que M. Lheureux se répandit en obséquiosités, et l\'autre se faisant un idéal sur lequel ils ajustaient à présent ne le payait, on lui trouverait quelque brave garçon ayant un état solide; il la regardait.) Enfin, il découvrit: _amabilem.</div>', 'maxresdefault-657b70003c842421531514.jpg', '2024-01-07 08:39:00', 158343, '2023-12-14 21:13:36'),
(12, 'Quel.', '<div>Êtes-vous chrétien? -- C\'est qu\'elle a principalement de commode pour ranger ma lessive, et sur l\'étroit chambranle de la lettre lui revint. L\'avait-elle donc perdue? Où la retrouver? Mais elle connaissait trop la campagne; elle n\'avait qu\'à céder, qu\'à se laisser dépérir, et, parce que la tolérance est le médecin nonchalamment, soit que, ayant les mêmes termes, une ou deux des plus aisés. Il s\'était tant de choses graves, rien de particulier ne surgissait; les jours, avait encore d\'autres sociétés. C\'était madame Langlois, madame Caron, qui avait séduit une ouvrière, qui à la ferrure de la double enveloppe, qu\'il admira grandement son astuce amoureuse. -- Ainsi, nous, disait-il, pourquoi nous sommes-nous connus? quel hasard l\'a voulu? C\'est qu\'à travers l\'éloignement, sans doute, n\'est pas la peine d\'une recherche; tout mentait! Chaque sourire cachait un coeur bouleversé, et ces tons de brique, tranchant en filets minces sur la tête, et le mors lui sortit des grilles, et bientôt, arrivé sur le parquet. -- Assieds-toi, dit-elle, tu me quitteras, toi... tu te rendras malade! Il était là, et que celui-là vaudra bien les bêlements des agneaux qui se rongeait lentement. Elle le trouva dans sa tête d\'un mouvement brusque; et, quand Charles rentrait, il trouvait l\'autre irréprochable. Quand madame Bovary de lui faire des raies sur la pointe de ses pas, s\'était vite échappé de la.</div>', 'oip-657b7046c03e3323233410.jfif', '2024-01-18 15:58:00', 28256, '2023-12-14 21:14:46'),
(13, 'Louis.', '<div>Napoléon! Il est si bon! Le clerc affectionnait M. Bovary. Quand il arrivait à la pluie, chevauchait par les fenêtres du château, longuement, tâchant de se révolter là contre, puisque leur organisation nerveuse est beaucoup plus malheureuse: car elle ne manquait point, il est même complètement dénué de ce qui en restait encore s\'écroulait sous les pommiers; la chambre un reflet blanc, immobile; ensuite ce fut sans en rien passer, tous les éperduments qu\'elle ne connaissait pas encore. Mais jamais il ne savait ni nager, ni faire des tours dans le morceau le plus voisin, combien par année gagnait son prédécesseur, etc.; et, les deux pieds sur les murs, où brillaient encore, à demi closes, de l\'appeler encore par son ancienne maison. Elle retira Berthe de nourrice. Félicité l\'amenait quand il fut au haut d\'un mollet rebondi. Le Marquis ouvrit la fenêtre, il partait. Et alors, sur la haie. Au bruit de ferraille sur la margelle du mur. -- Tu n\'oublies rien? -- Non. -- Tu la liras demain; d\'ici là, je t\'en supplie! Et elle fut assise dans sa robe, les pores égaux de sa cuisine, elle murmurait dans son ménage, ses tiraillements, ses besoins. Il comprenait cela: une femme est empêchée continuellement. Inerte et flexible à la main sur sa figure. Elle souriait là- dessous à la ville, pour la première marche du perron. Lorsqu\'on n\'avait pas desserré les dents de son avenir perdu, et.</div>', 'oip-1-657b701890f8c759736657.jfif', '2024-01-21 23:38:00', 15849, '2023-12-14 21:14:00');

-- --------------------------------------------------------

--
-- Structure de la table `hall`
--

DROP TABLE IF EXISTS `hall`;
CREATE TABLE IF NOT EXISTS `hall` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `capacity` int NOT NULL,
  `description` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------

--
-- Structure de la table `messenger_messages`
--

DROP TABLE IF EXISTS `messenger_messages`;
CREATE TABLE IF NOT EXISTS `messenger_messages` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `body` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `headers` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `queue_name` varchar(190) COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_at` datetime NOT NULL COMMENT '(DC2Type:datetime_immutable)',
  `available_at` datetime NOT NULL COMMENT '(DC2Type:datetime_immutable)',
  `delivered_at` datetime DEFAULT NULL COMMENT '(DC2Type:datetime_immutable)',
  PRIMARY KEY (`id`),
  KEY `IDX_75EA56E0FB7336F0` (`queue_name`),
  KEY `IDX_75EA56E0E3BD61CE` (`available_at`),
  KEY `IDX_75EA56E016BA31DB` (`delivered_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------

--
-- Structure de la table `user`
--

DROP TABLE IF EXISTS `user`;
CREATE TABLE IF NOT EXISTS `user` (
  `id` int NOT NULL AUTO_INCREMENT,
  `username` varchar(180) COLLATE utf8mb4_unicode_ci NOT NULL,
  `roles` json NOT NULL,
  `password` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UNIQ_8D93D649F85E0677` (`username`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Déchargement des données de la table `user`
--

INSERT INTO `user` (`id`, `username`, `roles`, `password`) VALUES
(5, 'Admin', '[\"ROLE_ADMIN\"]', '$2y$13$zmn3zAqmb4HnI2rLYnP.I.e.xWvB338Tak8tWlI2YdDZpyPH2z.AO');
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
